### ISSUE TITLE
need to update

### ISSUE THREAD

**Issue by hanbinChen97** [shing19/siri-gpt-notion#1]
针对

> 前提条件下
Notion API 和数据库 ID。您可以按照 [这里](https://juejin.cn/post/7067108031678545927) 的说明来获取。

这里使用notion api的方式，似乎没讲清楚，或者过时了。我半天没搞明白，XD。
官方教程更合适。
https://developers.notion.com/docs/create-a-notion-integration#step-2-share-a-database-with-your-integration

> Go to the database page in your workspace. (See our [Help Center articles](https://www.notion.so/help/category/databases) on databases to learn more about databases in Notion.)
Click the •••on the top right corner of the page.
Scroll to the bottom of the pop-up and click _Add connections_.
Search for and select your integration in the Search for connections... menu.

**Comment by shing19** [comment]
谢谢提供最新信息！已更新进文档
