### ISSUE TITLE
在“”中，找不到词典键“choices”的值。

### ISSUE THREAD

**Issue by xiaocheng-bili** [shing19/siri-gpt-notion#5]
如图。该填的值和网络环境都有准备好，尝试数次依然这样。求大佬帮忙看看教教谢谢
![IMG_5840](https://github.com/shing19/siri-gpt-notion/assets/74574034/8071d1a7-e9da-4050-8582-623c55c5bd72)

**Comment by shing19** [comment]
这是因为OpenAI没有返回正确信息，所以可能是网络问题、账号限制问题或者请求频率等问题。如果需要进一步诊断，则需要知道OpenAI具体返回了什么内容。

**Comment by xiaocheng-bili** [comment]
> 这是因为OpenAI没有返回正确信息，所以可能是网络问题、账号限制问题或者请求频率等问题。如果需要进一步诊断，则需要知道OpenAI具体返回了什么内容。

感谢你的回复，我查看了OpenAI API之后发现我的账户余额不足，这应该就是问题所在。
